// src/lib/mock-data.ts
// Mock data for local development without Supabase connection
// Source: https://noonnu.cc (2026-01-09 crawled)

import type { FontCardProps } from '@/types/font';

export const MOCK_FONTS: FontCardProps[] = [
  // 고딕/산세리프 계열
  {
    id: 'noonnu-694',
    name: '프리텐다드',
    foundry: '길형진 (orioncactus)',
    license_type: 'ofl',
    tags: ['산세리프', '기본 고딕', '본문', '9가지 굵기'],
    description: '크로스 플랫폼 system-ui 대체 글꼴. 가변 글꼴과 스태틱 글꼴 모두 제공.',
    source_url: 'https://noonnu.cc/font_page/694',
    views: 15420,
    price: 0,
  },
  {
    id: 'noonnu-366',
    name: 'G마켓 산스',
    foundry: 'G마켓',
    license_type: 'free',
    tags: ['산세리프', '제목용', '굵은', '3가지 굵기'],
    description: 'G마켓에서 제작한 무료 글꼴. 볼드한 느낌의 제목용 서체.',
    source_url: 'https://noonnu.cc/font_page/366',
    views: 12350,
    price: 0,
  },
  {
    id: 'noonnu-34',
    name: '본고딕 (Noto Sans KR)',
    foundry: 'Google×Adobe',
    license_type: 'ofl',
    tags: ['산세리프', '기본 고딕', '다국어', '7가지 굵기'],
    description: 'Google과 Adobe가 협력하여 개발한 오픈소스 글꼴.',
    source_url: 'https://noonnu.cc/font_page/34',
    views: 28930,
    price: 0,
  },
  {
    id: 'noonnu-223',
    name: '에스코어드림',
    foundry: 'S-Core',
    license_type: 'ofl',
    tags: ['산세리프', '기본 고딕', '9가지 굵기'],
    description: '다양한 굵기를 제공하는 고품질 고딕 폰트.',
    source_url: 'https://noonnu.cc/font_page/223',
    views: 9200,
    price: 0,
  },
  {
    id: 'noonnu-845',
    name: '수트 (SUIT)',
    foundry: 'SUNN YOUN',
    license_type: 'ofl',
    tags: ['산세리프', '기본 고딕', '9가지 굵기'],
    description: '현대적이고 깔끔한 고딕 폰트. 다양한 굵기 제공.',
    source_url: 'https://noonnu.cc/font_page/845',
    views: 8500,
    price: 0,
  },
  {
    id: 'noonnu-37',
    name: '나눔스퀘어',
    foundry: '네이버',
    license_type: 'ofl',
    tags: ['산세리프', '기본 고딕', '4가지 굵기'],
    description: '네이버에서 제작한 정사각형 비율의 고딕 폰트.',
    source_url: 'https://noonnu.cc/font_page/37',
    views: 11000,
    price: 0,
  },
  {
    id: 'noonnu-39',
    name: '나눔고딕',
    foundry: '네이버',
    license_type: 'ofl',
    tags: ['산세리프', '기본 고딕', '4가지 굵기'],
    description: '네이버에서 제작한 기본 고딕 폰트. 높은 가독성.',
    source_url: 'https://noonnu.cc/font_page/39',
    views: 18000,
    price: 0,
  },
  {
    id: 'noonnu-669',
    name: '카페24 써라운드',
    foundry: 'Cafe24',
    license_type: 'ofl',
    tags: ['산세리프', '둥근 고딕', '귀여운'],
    description: '둥글둥글한 귀여운 고딕 폰트.',
    source_url: 'https://noonnu.cc/font_page/669',
    views: 8320,
    price: 0,
  },
  // 세리프/바탕 계열
  {
    id: 'noonnu-41',
    name: '나눔명조',
    foundry: '네이버',
    license_type: 'ofl',
    tags: ['세리프', '명조', '전통'],
    description: '네이버에서 제작한 명조체. 한글의 전통적인 아름다움.',
    source_url: 'https://noonnu.cc/font_page/41',
    views: 9870,
    price: 0,
  },
  {
    id: 'noonnu-487',
    name: '마루 부리',
    foundry: '네이버',
    license_type: 'ofl',
    tags: ['세리프', '명조', '5가지 굵기'],
    description: '네이버에서 제작한 현대적인 세리프 폰트.',
    source_url: 'https://noonnu.cc/font_page/487',
    views: 7800,
    price: 0,
  },
  {
    id: 'noonnu-32',
    name: 'KoPub바탕',
    foundry: '한국출판인회의',
    license_type: 'ofl',
    tags: ['세리프', '바탕체', '본문'],
    description: '한국출판인회의에서 제작한 고품질 바탕체.',
    source_url: 'https://noonnu.cc/font_page/32',
    views: 6500,
    price: 0,
  },
  // 장식체/제목용
  {
    id: 'noonnu-115',
    name: '여기어때 잘난체',
    foundry: '여기어때컴퍼니',
    license_type: 'free',
    tags: ['장식체', '제목용', '굵은'],
    description: '매력만점 잘난체. 제목에 딱 맞는 폰트.',
    source_url: 'https://noonnu.cc/font_page/115',
    views: 6500,
    price: 0,
  },
  {
    id: 'noonnu-738',
    name: '어그로체',
    foundry: '(주)샌드박스네트워크',
    license_type: 'free',
    tags: ['장식체', '제목용', '임팩트', '3가지 굵기'],
    description: '어그로가 필요한 순간엔 어그로체를.',
    source_url: 'https://noonnu.cc/font_page/738',
    views: 5400,
    price: 0,
  },
  {
    id: 'noonnu-1500',
    name: '꾸불림체',
    foundry: '우아한형제들',
    license_type: 'ofl',
    tags: ['장식체', '개성', '히피'],
    description: '꾸불꾸불한 히피펌같은 글꼴.',
    source_url: 'https://noonnu.cc/font_page/1500',
    views: 4100,
    price: 0,
  },
  // 손글씨/캘리
  {
    id: 'noonnu-53',
    name: '주아체',
    foundry: '우아한형제들',
    license_type: 'ofl',
    tags: ['손글씨', '귀여운', '캐주얼'],
    description: '우아한형제들에서 제작한 손글씨 폰트.',
    source_url: 'https://noonnu.cc/font_page/53',
    views: 7200,
    price: 0,
  },
  {
    id: 'noonnu-1663',
    name: '메모먼트 꾹꾹체',
    foundry: '메모먼트',
    license_type: 'free',
    tags: ['손글씨', '귀여운', '일기'],
    description: '꾹꾹 눌러 쓴 듯한 손글씨 폰트.',
    source_url: 'https://noonnu.cc/font_page/1663',
    views: 3200,
    price: 0,
  },
  // 레트로/픽셀
  {
    id: 'noonnu-250',
    name: '둥근모꼴+ Fixedsys',
    foundry: '길형진 (orioncactus)',
    license_type: 'ofl',
    tags: ['픽셀', '레트로', '코딩'],
    description: '90년대 PC통신에 쓰이던 고전 폰트.',
    source_url: 'https://noonnu.cc/font_page/250',
    views: 6000,
    price: 0,
  },
  // 지역 특화
  {
    id: 'noonnu-1032',
    name: '제주돌담체',
    foundry: '얼리폰트',
    license_type: 'free',
    tags: ['장식체', '지역', '제주'],
    description: '제주도의 돌담을 모티브로 한 폰트.',
    source_url: 'https://noonnu.cc/font_page/1032',
    views: 2800,
    price: 0,
  },
];

/**
 * Check if we should use mock data (when Supabase credentials are placeholder values)
 */
export function shouldUseMockData(): boolean {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  return !supabaseUrl || supabaseUrl.includes('xxxx') || supabaseUrl === 'https://xxxx.supabase.co';
}
